from manim import *

config.background_color = "#141414"

class BinomialTheorem(Scene):
    def construct(self):
         intro = Tex("Proving: Binomial Theorem").shift(2*UP).scale(1.5)
         logo = MathTex(r" \left< \psi \right>").to_corner(UR,buff=0.6).set_color(PURPLE_A)
         self.add(logo)
         self.play(Write(intro),run_time=2)
         bino = MathTex("(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^k b^{n-k}")
         bino.set_width(5)
         bino[0][1].set_color(YELLOW)
         bino[0][3].set_color(BLUE)
         bino[0][16].set_color(YELLOW)
         bino[0][18].set_color(BLUE)
         bino.next_to(intro, DOWN, buff=0.2)
         bino_sur = SurroundingRectangle(bino, color=PURPLE_A)
         self.play(FadeIn(bino, shift=UP),run_time=0.8)
         self.wait(0.4)
         self.play(Create(bino_sur),run_time=1.2,rate_func=linear)
         self.wait(1)
         self.play(Uncreate(bino_sur))
         self.wait(0.5)
         self.play(intro.animate.shift([0,1.5,0]).scale(0.6))
         self.play(bino.animate.shift([0,1.5,0]))
         self.wait()
         
         note = Tex(r"Note: n = 0,1 = $\displaystyle \binom{0}{0}a^0b^0$").match_width(bino)
         note.next_to(bino,DOWN,buff=0.1)
         note[0][15].set_color(YELLOW)
         note[0][17].set_color(BLUE)
         
   #      self.add(index_labels(note[0])) Finding Index Number
         self.play(Write(note),run_time=2.5)
         self.wait(1.3)
         
         by = Tex("By Induction: ").set_width(3)
         by.next_to(note,DOWN,buff=0.28)
         self.play(Write(by))
         self.wait(1.9820)
         
         ass = Tex("Assuming it works for n+1").set_width(6).next_to(by, DOWN, buff=0.28)
         self.play(FadeIn(ass))
         self.wait()
         self.play(*map(FadeOut, [bino, note, by, ass]))
         self.wait()
         
         equ1 = MathTex(r"(a+b)^n = a^n + \binom{n}{1} a^{n-1}b\cdots \binom{n}{n-1}ab^{n-1}+b^n")
         equ1[0][1].set_color(YELLOW)
         equ1[0][3].set_color(BLUE)
         equ1[0][14].set_color(YELLOW)
         equ1[0][18].set_color(BLUE)
         equ1[0][28].set_color(YELLOW)
         equ1[0][29].set_color(BLUE)
         equ1[0][34].set_color(BLUE)
         equ1.next_to(intro, DOWN,buff=0.2)
         self.play(Write(equ1),run_time=2.1)
         self.wait(2)
         equ2 = MathTex(r"(a+b)^{n+1} = (a+b)(a+b)^n").next_to(equ1,DOWN,buff=0.2)
         equ2[0][1].set_color(YELLOW)
         equ2[0][3].set_color(BLUE)
         equ2[0][10].set_color(YELLOW)
         equ2[0][12].set_color(BLUE)
         equ2[0][15].set_color(YELLOW)
         equ2[0][17].set_color(BLUE)
         self.play(Write(equ2),run_time=3)
         self.wait(3)
         
         equ3 = MathTex(r" = (a+b)(a^n+\binom{n}{1}a^{n-1}b\cdots\binom{n}{n-1}ab^{n-1}+b^n)")
         equ3.next_to(equ2,DOWN,buff=0.2)
         equ3[0][2].set_color(YELLOW)
         equ3[0][4].set_color(BLUE)
         equ3[0][7].set_color(YELLOW)
         equ3[0][14].set_color(YELLOW)
         equ3[0][18].set_color(BLUE)
         equ3[0][28].set_color(YELLOW)
         equ3[0][29].set_color(BLUE)
         equ3[0][34].set_color(BLUE)
         self.play(Write(equ3),run_time=4)
         self.wait(2)
         
         equ4 = MathTex(r"a^{n+1}+[1+\binom{n}{1}]a^nb+[\binom{n}{1}+\binom{n}{2}]a^{n-1}b^2+\cdots")
         equ4.next_to(equ3,DOWN,buff=0.2)
         equ4[0][0].set_color(YELLOW)
         equ4[0][13].set_color(YELLOW)
         equ4[0][15].set_color(BLUE)
         equ4[0][28].set_color(YELLOW)
         equ4[0][32].set_color(BLUE)
         self.play(Write(equ4),run_time=4)
         self.wait(2)
         
         equ5 = MathTex(r"\cdots+[\binom{n}{r-1}+\binom{n}{r}]a^{n-r+1}b^r+\cdots")
         equ5.next_to(equ4,DOWN,buff=0.2)
         equ5[0][-6].set_color(BLUE)
         equ5[0][-12].set_color(YELLOW)
         self.play(Write(equ5),run_time=2)
         self.wait()
         self.play(*map(FadeOut, [equ1, equ2, equ3, equ4, equ5]))
               
         
         equ6 = MathTex(r"\cdots+[\binom{n}{n-1}+1]ab^k+b^{k+1}")
         equ6.next_to(intro,DOWN,buff=0.2)
         equ6[0][-4].set_color(BLUE)
         equ6[0][-7].set_color(BLUE)
         equ6[0][-8].set_color(YELLOW)
         self.play(Write(equ6),run_time=1.8)
         self.wait(1.9792)
         
         pas = VGroup(Tex("Pascal's Identity: "),
                        MathTex(r"\binom{n}{k-1}+\binom{n}{k}=\binom{n+1}{k}"))
         pas.arrange(RIGHT)
         pas.next_to(equ6,DOWN,buff=0.2)
         pas[0].set_color("#8D70C7")
         pas[1].set_color("#8D70C7")
         self.play(Write(pas))
         self.wait(2)
         self.play(FadeOut(pas))
         self.wait()
         
         equ7 = MathTex(r"=a^{n+1}+\binom{n+1}{1}a^nb+\cdots+\binom{n+1}{n}ab^n+b^{n+1}")
         equ7.next_to(equ6,DOWN,buff=0.2)
         equ7[0][1].set_color(YELLOW)
         equ7[0][12].set_color(YELLOW)
         equ7[0][14].set_color(BLUE)
         equ7[0][-4].set_color(BLUE)
         equ7[0][-7].set_color(BLUE)
         equ7[0][-8].set_color(YELLOW)
         self.play(Write(equ7),run_time=2)
         self.wait(2)
         
         equ8 = MathTex(r"\sum_{k=0}^{n}a^kb^{n+1-k}")
         equ8.next_to(equ7,DOWN,buff=0.2)
         equ8[0][8].set_color(YELLOW)
         equ8[0][10].set_color(BLUE)
         self.play(Write(equ8),run_time=2.12827)
         self.wait()
         
         self.play(*map(FadeOut, [equ6, equ7]))
         self.wait()              
        
         self.play(equ8.animate.scale(1.57).shift([0,0,0]))
         last_sur = SurroundingRectangle(equ8)
         self.play(Create(last_sur))
         self.wait(4)
         
class Thumbnail(Scene):
    def construct(self):
        bino = MathTex("(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^k b^{n-k}").set_width(config.frame_width - 2)
        bino_sur = SurroundingRectangle(bino,color="#8D70C7",buff=0.2)
        tex = Tex("Proving: Binomial Theorem").shift(3*UP).scale(1.62)
        self.add(bino, bino_sur, tex)
